@startuml

participant Jugador as J
participant BatallaNaval as B

J -> B: jugarBatallaNaval()

B -> B: crearTablero(4, 4)
B -> B: elegirUbicacionAleatoria(tablero)

loop while true
    B -> J: mostrarTablero(tablero)
    J -> B: obtenerIntento()
    B -> B: esIgual(intento, ubicacionBarco)
    alt Tocado y hundido
        B -> B: marcarTocadoYHundido(tablero, intento)
        B -> J: mostrarTablero(tablero)
        J -> B: "Tocado y hundido - ¡Has ganado!\n"
    else
        B -> B: marcarAgua(tablero, intento)
        J -> B: "Agua - Intenta de nuevo.\n"
    end
end

@enduml