@startuml
title Sistema de Análisis de Calificaciones

participant Usuario
participant Sistema

Usuario -> Sistema: Ingresar nota
loop while(Nota != -1)
    Sistema -> Usuario: Mostrar mensaje para ingresar nota
    Usuario -> Sistema: Ingresar nota
    Sistema -> Sistema: Almacenar nota
end

Sistema -> Sistema: Calcular media
Sistema -> Usuario: Mostrar calificaciones
Sistema -> Usuario: Mostrar media

@enduml
